name: Cocogitto
on:
  push:
    branches: [master]
  pull_request:

jobs:
  cog_check_job:
    runs-on: ubuntu-latest
    name: check conventional commit compliance
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Conventional commits check
        uses: oknozor/cocogitto-action@v3
        with:
          check-latest-tag-only: true
      - name: Semver release
        uses: oknozor/cocogitto-action@v3
        with:
          release: true
          git-user: 'glucrypto'
          git-user-email: 'glucrypto@protonmail.com'
      - name: Generate Changelog
        run: cog changelog --at ${{ steps.release.outputs.version }} -t full_hash > CHANGELOG.md